### ISSUE TITLE
gradle in main tree?

### ISSUE THREAD

**Issue by nicolasbock** [gentoo/java-overlay#28] opened 2015-12-28 20:55 UTC
Hi, what are the prospects of adding gradle to the main tree? 

Thanks already,

Nick

**Comment by chewi** [comment] 2015-12-28 23:06
Unlikely in the short term unless @Flowdalic becomes an official dev, I'm afraid. The problem is less Gradle itself and more the software using it. We need to build such software in a sane way and that isn't trivial to do. Maven is also a bigger priority. Until there is something in the tree that really needs Gradle, there is little incentive for us to maintain it, especially if someone is already doing it in the overlay.

**Comment by nicolasbock** [comment] 2016-01-20 12:52
I am maintaining app-text/jabref, which would require gradle to build. But I am not aware of any other project that would require gradle.

**Comment by chewi** [comment] 2016-01-20 13:03
It was noted the other day that Groovy is using it that's not how we're building it now and that's presented at least one minor issue.

**Comment by Flowdalic** [comment] 2016-01-20 13:03
> Unlikely in the short term unless @Flowdalic becomes an official dev

Me being a dev or not is not a factor. I'm already maintaining a few in-tree ebuilds with the help of proxy maintainers.

> The problem is less Gradle itself

Depends. Gradle comes with a ton of bundled libraries. I aware of Gentoo's policy about those and unbundling, and, while I fully aggree with it, if it is fully enforced in Gradle's case, I don't see an ebuild for it in tree anytime soon.

Looking at the bigger picture, what is really required, not only for Gentoo is a system-wide local Maven repository managed by the distributions package manager. So that we don't have to unbundle jar's for all eternity.

**Comment by Flowdalic** [comment] 2016-01-21 10:04
I suggest to close this issue at github and redirect people to https://bugs.gentoo.org/show_bug.cgi?id=339574. No need to have fragmented discussion of the same topic all over the place.

**Closed** 2016-01-21 11:23 UTC

**Comment by mmokrejs** [comment] 2016-07-12 21:25
BTW, I just hit the gradle, for a full story read https://github.com/samtools/htsjdk/issues/377
